# Generated by Django 2.2.12 on 2022-05-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumValueReceta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbohidratos', models.CharField(max_length=30)),
                ('proteinas', models.CharField(max_length=30)),
                ('grasas', models.CharField(max_length=30)),
                ('kcal', models.CharField(max_length=30)),
                ('alcohol', models.CharField(max_length=30)),
                ('cafeina', models.CharField(max_length=30)),
                ('cobre', models.CharField(max_length=30)),
                ('calcio', models.CharField(max_length=30)),
                ('fluor', models.CharField(max_length=30)),
                ('vitA', models.CharField(max_length=30)),
                ('vitB1', models.CharField(max_length=30)),
                ('vitB2', models.CharField(max_length=30)),
                ('vitB3', models.CharField(max_length=30)),
                ('vitB5', models.CharField(max_length=30)),
                ('vitB6', models.CharField(max_length=30)),
                ('vitB12', models.CharField(max_length=30)),
                ('vitC', models.CharField(max_length=30)),
                ('vitD', models.CharField(max_length=30)),
                ('vitE', models.CharField(max_length=30)),
                ('vitK', models.CharField(max_length=30)),
                ('fibra', models.CharField(max_length=30)),
                ('acFolico', models.CharField(max_length=30)),
                ('hierro', models.CharField(max_length=30)),
                ('magnesio', models.CharField(max_length=30)),
                ('manganeso', models.CharField(max_length=30)),
                ('fosforo', models.CharField(max_length=30)),
                ('potasio', models.CharField(max_length=30)),
                ('selenio', models.CharField(max_length=30)),
                ('sodio', models.CharField(max_length=30)),
                ('azucar', models.CharField(max_length=30)),
                ('zinc', models.CharField(max_length=30)),
            ],
        ),
    ]
