# Generated by Django 2.2.12 on 2022-05-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numvaluereceta',
            name='idSpoon',
            field=models.CharField(default='', max_length=50),
        ),
    ]
