# Generated by Django 2.2.12 on 2022-05-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_numvaluereceta_idspoon'),
    ]

    operations = [
        migrations.AddField(
            model_name='numvaluereceta',
            name='servings',
            field=models.CharField(default='', max_length=50),
        ),
    ]
