# Generated by Django 2.2.12 on 2022-05-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_numvaluereceta_servings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numvaluereceta',
            old_name='acFolico',
            new_name='colesterol',
        ),
        migrations.AddField(
            model_name='numvaluereceta',
            name='receta',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='numvaluereceta',
            name='saturedFat',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
