# Generated by Django 2.2.12 on 2022-06-01 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20220531_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numvaluereceta',
            old_name='receta',
            new_name='recetas',
        ),
    ]
