# Generated by Django 2.2.12 on 2022-06-01 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20220601_0646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numvaluereceta',
            old_name='recetas',
            new_name='receta',
        ),
    ]
