# Generated by Django 2.2.12 on 2022-06-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20220601_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumValueIngrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('IdSpoon', models.CharField(max_length=30)),
                ('Carbohidratos', models.CharField(max_length=30)),
                ('Proteinas', models.CharField(max_length=30)),
                ('Grasas', models.CharField(max_length=30)),
                ('Kcal', models.CharField(max_length=30)),
                ('Alcohol', models.CharField(max_length=30)),
                ('Cafeina', models.CharField(max_length=30)),
                ('Cobre', models.CharField(max_length=30)),
                ('Calcio', models.CharField(max_length=30)),
                ('Colesterol', models.CharField(max_length=30)),
                ('Fluor', models.CharField(max_length=30)),
                ('GrasasSaturadas', models.CharField(max_length=30)),
                ('VitA', models.CharField(max_length=30)),
                ('VitC', models.CharField(max_length=30)),
                ('VitD', models.CharField(max_length=30)),
                ('VitE', models.CharField(max_length=30)),
                ('VitK', models.CharField(max_length=30)),
                ('VitB1', models.CharField(max_length=30)),
                ('VitB2', models.CharField(max_length=30)),
                ('VitB3', models.CharField(max_length=30)),
                ('VitB5', models.CharField(max_length=30)),
                ('VitB6', models.CharField(max_length=30)),
                ('VitB12', models.CharField(max_length=30)),
                ('Fibra', models.CharField(max_length=30)),
                ('Folato', models.CharField(max_length=30)),
                ('AcFolico', models.CharField(max_length=30)),
                ('Hierro', models.CharField(max_length=30)),
                ('Magnesio', models.CharField(max_length=30)),
                ('Manganeso', models.CharField(max_length=30)),
                ('Fosforo', models.CharField(max_length=30)),
                ('Potasio', models.CharField(max_length=30)),
                ('Selenio', models.CharField(max_length=30)),
                ('Sodio', models.CharField(max_length=30)),
                ('Azucar', models.CharField(max_length=30)),
                ('Zinc', models.CharField(max_length=30)),
            ],
        ),
    ]
